name: Tests
on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - run: yarn test
